default: &default
  encoding: utf8
  adapter: postgresql
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= (ENV['DATABASE_URL'] || '') %>

development:
  <<: *default
  database: burnlog_dev
  username: root

test:
  <<: *default
  database: burnlog_test
  username: root
